cloud_id = "My_deployment:ZXVyb3BlLXdlc3QxLmdjcC5jbG91ZC5lcy5pbyQ0N2JhMTAxNjhmMzg0M2MwODE1YTU4MzMxZTEwYTc5OSQ1ZDY0YTg0YzI3MjU0NjA1YTg1OWYwNTcwZDRiZTI3MA=="
api_key_1 = "4M42-IgBTdLMf-o42MtL"
api_key_2 = "u2FMsPOUSv2RBwnQXxsC6g"
jobIndex = "search-mirror-mission"
profilIndex = "search-5-min-profile-1"
graphQL = "https://app-dev-wyew76oo4a-ew.a.run.app/graphql?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAKoDO+RwAOkkaRXlbffQJZgusAO+ZESAIYAbACKCUg5nVb0EcQW2HTZsgG4jcXWQF9tRPTMM6QAGhAa8bQQCNhCMhhAgdQA"
password = "prom@n1!"